apiVersion: v1
kind: Service
metadata:
  name: {{ include "setu-gateway.gatewayName" . }}
  labels:
    {{- include "setu-gateway.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "setu-gateway.gatewaySelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.port }}
  type: ClusterIP
