"""add cache, time machine, and scoped api key tables/columns

Revision ID: 2e926fd2719a
Revises: e98f0dd8f3ff
Create Date: 2026-08-01 23:22:19.725959

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e926fd2719a"
down_revision: str | Sequence[str] | None = "e98f0dd8f3ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("is_streaming", sa.Boolean(), nullable=False),
        sa.Column("stream_chunks", sa.JSON(), nullable=True),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cache_entries_cache_key"), "cache_entries", ["cache_key"], unique=True)
    op.create_index(op.f("ix_cache_entries_expires_at"), "cache_entries", ["expires_at"], unique=False)
    op.create_index(op.f("ix_cache_entries_project_id"), "cache_entries", ["project_id"], unique=False)
    op.create_table(
        "cache_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("ttl_seconds", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_table(
        "time_machine_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("requested_model", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("upstream_model", sa.String(length=255), nullable=False),
        sa.Column("request_messages", sa.JSON(), nullable=False),
        sa.Column("request_params", sa.JSON(), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_time_machine_records_created_at"), "time_machine_records", ["created_at"], unique=False)
    op.create_index(op.f("ix_time_machine_records_organization_id"), "time_machine_records", ["organization_id"], unique=False)
    op.create_index(op.f("ix_time_machine_records_project_id"), "time_machine_records", ["project_id"], unique=False)
    op.create_index(op.f("ix_time_machine_records_request_id"), "time_machine_records", ["request_id"], unique=True)
    op.add_column("api_keys", sa.Column("permissions", sa.JSON(), nullable=True))
    op.add_column("api_keys", sa.Column("allowed_ips", sa.JSON(), nullable=True))
    op.add_column("api_keys", sa.Column("allowed_providers", sa.JSON(), nullable=True))
    op.add_column("api_keys", sa.Column("allowed_models", sa.JSON(), nullable=True))
    op.add_column("api_keys", sa.Column("rate_limit_per_minute", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_keys", "rate_limit_per_minute")
    op.drop_column("api_keys", "allowed_models")
    op.drop_column("api_keys", "allowed_providers")
    op.drop_column("api_keys", "allowed_ips")
    op.drop_column("api_keys", "permissions")
    op.drop_index(op.f("ix_time_machine_records_request_id"), table_name="time_machine_records")
    op.drop_index(op.f("ix_time_machine_records_project_id"), table_name="time_machine_records")
    op.drop_index(op.f("ix_time_machine_records_organization_id"), table_name="time_machine_records")
    op.drop_index(op.f("ix_time_machine_records_created_at"), table_name="time_machine_records")
    op.drop_table("time_machine_records")
    op.drop_table("cache_policies")
    op.drop_index(op.f("ix_cache_entries_project_id"), table_name="cache_entries")
    op.drop_index(op.f("ix_cache_entries_expires_at"), table_name="cache_entries")
    op.drop_index(op.f("ix_cache_entries_cache_key"), table_name="cache_entries")
    op.drop_table("cache_entries")
    # ### end Alembic commands ###
