"""add project_id and requested_model index to request_logs

Revision ID: 3d33b2e11564
Revises: dbd462f822b9
Create Date: 2026-08-01 23:57:45.681242

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d33b2e11564"
down_revision: str | Sequence[str] | None = "dbd462f822b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("request_logs", sa.Column("project_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_request_logs_project_id"), "request_logs", ["project_id"], unique=False)
    op.create_index(op.f("ix_request_logs_requested_model"), "request_logs", ["requested_model"], unique=False)
    op.create_foreign_key("fk_request_logs_project_id_projects", "request_logs", "projects", ["project_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_request_logs_project_id_projects", "request_logs", type_="foreignkey")
    op.drop_index(op.f("ix_request_logs_requested_model"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_project_id"), table_name="request_logs")
    op.drop_column("request_logs", "project_id")
    # ### end Alembic commands ###
