"""add billing quota fields to organizations

Revision ID: 54dbecd19969
Revises: 3d33b2e11564
Create Date: 2026-08-02 00:01:50.866364

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54dbecd19969"
down_revision: str | Sequence[str] | None = "3d33b2e11564"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organizations", sa.Column("monthly_request_quota", sa.Integer(), nullable=True))
    op.add_column("organizations", sa.Column("monthly_spend_quota_usd", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "monthly_spend_quota_usd")
    op.drop_column("organizations", "monthly_request_quota")
    # ### end Alembic commands ###
