"""add prompt template tables

Revision ID: cc6e2b5d2126
Revises: a11d92b1b78b
Create Date: 2026-08-02 13:55:53.558630

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc6e2b5d2126"
down_revision: str | Sequence[str] | None = "a11d92b1b78b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("messages", sa.JSON(), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prompt_templates_organization_id"), "prompt_templates", ["organization_id"], unique=False)
    op.create_table(
        "prompt_template_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("messages", sa.JSON(), nullable=False),
        sa.Column("change_note", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["template_id"], ["prompt_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("template_id", "version", name="uq_prompt_template_versions_template_version"),
    )
    op.create_index(op.f("ix_prompt_template_versions_created_at"), "prompt_template_versions", ["created_at"], unique=False)
    op.create_index(op.f("ix_prompt_template_versions_template_id"), "prompt_template_versions", ["template_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prompt_template_versions_template_id"), table_name="prompt_template_versions")
    op.drop_index(op.f("ix_prompt_template_versions_created_at"), table_name="prompt_template_versions")
    op.drop_table("prompt_template_versions")
    op.drop_index(op.f("ix_prompt_templates_organization_id"), table_name="prompt_templates")
    op.drop_table("prompt_templates")
    # ### end Alembic commands ###
