"""add rate limit rules table

Revision ID: dbd462f822b9
Revises: 2e926fd2719a
Create Date: 2026-08-01 23:51:35.093234

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbd462f822b9"
down_revision: str | Sequence[str] | None = "2e926fd2719a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope_type", sa.String(length=20), nullable=False),
        sa.Column("scope_value", sa.String(length=255), nullable=True),
        sa.Column("algorithm", sa.String(length=20), nullable=False),
        sa.Column("limit", sa.Integer(), nullable=False),
        sa.Column("window_seconds", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rate_limit_rules_scope_type"), "rate_limit_rules", ["scope_type"], unique=False)
    op.create_index(op.f("ix_rate_limit_rules_scope_value"), "rate_limit_rules", ["scope_value"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rate_limit_rules_scope_value"), table_name="rate_limit_rules")
    op.drop_index(op.f("ix_rate_limit_rules_scope_type"), table_name="rate_limit_rules")
    op.drop_table("rate_limit_rules")
    # ### end Alembic commands ###
