FROM node:20-alpine as base

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-workspace.yaml package.json pnpm-lock.yaml* ./
COPY apps/dashboard ./apps/dashboard
COPY packages ./packages

RUN pnpm install --frozen-lockfile

EXPOSE 3000

CMD ["pnpm", "--filter", "@setu/dashboard", "dev"]
